// Basket Action Types
export const FETCH_BASKET_REQUEST = 'FETCH_BASKET_REQUEST';
export const FETCH_BASKET_SUCCESS = 'FETCH_BASKET_SUCCESS';
export const FETCH_BASKET_FAILURE = 'FETCH_BASKET_FAILURE';

export const ADD_TO_BASKET_REQUEST = 'ADD_TO_BASKET_REQUEST';
export const ADD_TO_BASKET_SUCCESS = 'ADD_TO_BASKET_SUCCESS';
export const ADD_TO_BASKET_FAILURE = 'ADD_TO_BASKET_FAILURE';

export const UPDATE_BASKET_ITEM_REQUEST = 'UPDATE_BASKET_ITEM_REQUEST';
export const UPDATE_BASKET_ITEM_SUCCESS = 'UPDATE_BASKET_ITEM_SUCCESS';
export const UPDATE_BASKET_ITEM_FAILURE = 'UPDATE_BASKET_ITEM_FAILURE';

export const REMOVE_FROM_BASKET_REQUEST = 'REMOVE_FROM_BASKET_REQUEST';
export const REMOVE_FROM_BASKET_SUCCESS = 'REMOVE_FROM_BASKET_SUCCESS';
export const REMOVE_FROM_BASKET_FAILURE = 'REMOVE_FROM_BASKET_FAILURE';

export const CLEAR_BASKET_REQUEST = 'CLEAR_BASKET_REQUEST';
export const CLEAR_BASKET_SUCCESS = 'CLEAR_BASKET_SUCCESS';
export const CLEAR_BASKET_FAILURE = 'CLEAR_BASKET_FAILURE';

export const CLEAR_BASKET_ERROR = 'CLEAR_BASKET_ERROR';

// Local storage basket actions (for non-authenticated users)
export const ADD_TO_LOCAL_BASKET = 'ADD_TO_LOCAL_BASKET';
export const UPDATE_LOCAL_BASKET_ITEM = 'UPDATE_LOCAL_BASKET_ITEM';
export const REMOVE_FROM_LOCAL_BASKET = 'REMOVE_FROM_LOCAL_BASKET';
export const LOAD_LOCAL_BASKET = 'LOAD_LOCAL_BASKET';
export const CLEAR_LOCAL_BASKET = 'CLEAR_LOCAL_BASKET';
