@baseUrl = http://localhost:8080
@token = bananabananabanana

### 1. Register a new user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "johndoe",
  "email": "john@example.com",
  "password": "password123",
  "roleId": 1,
  "phoneNumber": "123-456-7890",
  "address": {
    "zip": "12345",
    "country": "USA",
    "street": "123 Main St",
    "province": "NY"
  }
}

### 1. Register a new user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "johnfdfasfsfdoe",
  "email": "john@exaasfasfasmpfffle.com",
  "password": "password123",
  "roleId": 1,
  "phoneNumber": "123-456-7890",
  "address": {
    "zip": "12345",
    "country": "USA",
    "street": "123 Main St",
    "province": "NY"
  }
}


### 2. Register admin user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@example.com",
  "password": "admin123",
  "roleId": 2,
  "phoneNumber": "987-654-3210",
  "address": {
    "zip": "54321",
    "country": "USA",
    "street": "456 Admin Ave",
    "province": "CA"
  }
}

###

### 3. Login (Copy the token from response and paste it in the @token variable above)
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "password123"
}

###

### 4. Login as admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123"
}


### 5. Validate Token (Get current user info)
GET {{baseUrl}}/api/auth/validate
Authorization: Bearer {{token}}

